name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black pytest

      - name: Lint and format check
        run: |
          flake8 --config .flake8 .
          black --check .

      - name: Run tests
        run: |
          pytest -v

      - name: Build Docker image
        if: ${{ hashFiles('Dockerfile') != '' }}
        run: docker build -t jarvis .
